kind: Secret
apiVersion: v1
type: kubernetes.io/basic-auth
metadata:
  name: cluster-alternative-hmo
  namespace: openshift-gitops
  labels:
    #argocd.argoproj.io/secret-type: cluster
    enviroment: nop
stringData:
  config: test
  name: test
  server: https://kubernetes.default.svc