kind: Secret
apiVersion: v1
metadata:
  name: cluster-alternative-hmo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
    enviroment: nop
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
type: Opaque