---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  sources:
    - repoURL: https://github.com/seranpol/app-auto.git
      path: argocd-app-of-apps
      targetRevision: main
      helm:
        valueFiles:
        - "https://github.com/seranpol/app-value.git/operators-and-configs.yaml"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true