---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  sources:
    - repoURL: https://github.com/seranpol/app-auto.git
      path: helm-charts/charts/argocd-app-of-apps
      targetRevision: main
      helm:
        valueFiles:
        - "$valueRepo/bootstrap/operators-and-configs.yaml"
        parameters:
        - name: globalAutomationRepoURL
          value: https://github.com/seranpol/app-auto.git
        - name: globalClusterRepoURL
          value: https://github.com/seranpol/app-value.git

    - repoURL: https://github.com/seranpol/app-value.git
      ref: valueRepo
      targetRevision: main

      
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true