{{- if .Values.clustergenerators }}
{{- range $i, $app := .Values.clustergenerators }}
{{- if hasKey $app "enabled" | ternary $app.enabled $.Values.default.app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: openshift-gitops
spec:
  # project can not be defined here - seems like we can't control the project of the ApplicationSet
  # project: default
  generators:
    {{- range $env := .environments }}
    - clusters:
        selector:
          matchLabels:
            enviroment: {{ $env }}
        # can't be used https://github.com/argoproj/argo-cd/issues/16830
        values:
          clusterEnvironment: {{ $env }}
    {{- end }}
  template:
    metadata:
      name: {{.name}}-clustergenerator-{{ $i }}
      namespace: default
      #namespace: {{ (.destination).namespace }}
    spec:    
      project: {{ .project | default $.Values.default.app.project }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      destination:
        #name: 'in-cluster' - this works
        server: {{ (.destination).server | default $.Values.default.app.destination.server | required (printf "No destination.server specified") }}

        #namespace: openshift-gitops
        namespace: {{ (.destination).namespace | default $.Values.default.app.destination.namespace | required (printf "No destination.namespace specified") }}

      source:
        repoURL: {{ $.Values.globalAutomationRepoURL }}
        path: helm-charts/charts/argocd-app-of-apps
        targetRevision: main        
        helm:
          valuesObject:
            applications: {{ $app.generatorApplications | toYaml | nindent 14 }}
          parameters:
            - name: globalAutomationRepoURL
              value: {{ $.Values.globalAutomationRepoURL }}
            - name: globalClusterRepoURL
              value: {{ $.Values.globalClusterRepoURL }}
            - name: app
              value: {{ $.Values.default.app }}
{{- end }}
{{- end }}
{{- end }}