{{- if .Values.clustergenerators }}
{{- range $i, $app := .Values.clustergenerators }}
{{- if hasKey $app "enabled" | ternary $app.enabled $.Values.default.app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: {{.namespace}}
spec:
  generators:
    {{- range $env := .environments }}
    - clusters:
        selector:
          matchLabels:
            enviroment: {{ $env }}
        values:
          clusterEnvironment: {{ $env }}
    {{- end }}
  template:
    metadata:
      name: clustergenerator-{{ $i }}
      namespace: {{ (.destination).namespace }}
    spec:    
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      destination:
        #name: 'https://kubernetes.default.svc'
        name: 'in-cluster'
        namespace: openshift-gitops
      source:
        repoURL: {{ $.Values.globalAutomationRepoURL }}
        path: helm-charts/charts/argocd-app-of-apps
        targetRevision: main        
        helm:
          valuesObject:
            applications: {{ $app.generatorApplications | toYaml | nindent 14 }}
          parameters:
            - name: globalAutomationRepoURL
              value: {{ $.Values.globalAutomationRepoURL }}
            - name: globalClusterRepoURL
              value: {{ $.Values.globalClusterRepoURL }}
            - name: test
              value: {{ generators.clusters.values.clusterEnvironment }}

            
{{- end }}
{{- end }}
{{- end }}