default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    retry:
      limit: 30
      backoff:
        duration: 5s
        maxDuration: 10m0s
        factor: 2
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true